### ISSUE TITLE
Safari browser || Home page distorted due to previous asked question  

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#100]
When I tried opening ask.astronomer.io is safari UI show this

![image](https://github.com/astronomer/ask-astro/assets/43964496/7105cacd-c243-4200-920f-e4c4e6129814)

**Comment by sunank200** [comment]
I opened it on Safari as well, but shows fine to me. How can i replicate this?

![Screenshot 2023-11-09 at 2 37 15 PM](https://github.com/astronomer/ask-astro/assets/8670962/32d9dbc9-408c-4b18-8825-3efff1fa3411)

**Comment by vatsrahul1001** [comment]
@sunank200 which safari version you are on?

**Comment by sunank200** [comment]
@vatsrahul1001 `Version 17.1 (19616.2.9.11.7)`

**Comment by vatsrahul1001** [comment]
I am on Version 15.1 (17612.2.9.1.20)

**Comment by pankajastro** [comment]
maybe you should try to clean the cache once update the browser too 15.x was released 2 years ago and since then we should couple of major version

**Comment by phanikumv** [comment]
@vatsrahul1001 to mention replication steps for this

**Comment by vatsrahul1001** [comment]
Not able to reproduce it on latest safari, closing this
