### ISSUE TITLE
Ask Astro || Incorrect response for query: Tell me how can I check task logs with airflow CLI

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#101]
In Airflow CLI we do not have any logs command in tasks, and the response is totally incorrect

Response i have received from Ask Astro

To check task logs with the Airflow CLI, you will need to use the Airflow tasks logs command. Here is the basic syntax:
airflow tasks logs -A -t [task_id] [dag_id] [execution_date]
• Replace [task_id] with the ID of the task you want to view logs for.
• Replace [dag_id] with the ID of the DAG that the…
See more

**Comment by sunank200** [comment]
We have not ingested [https://github.com/kaxil/airflowctl](https://github.com/kaxil/airflowctl ) to this deployment

**Comment by phanikumv** [comment]
Then response should be something like what chapgpt says for unknown topics.."As of my last knowledge update in 2023, I dont have access to this information"

**Comment by davidgxue** [comment]
https://ask.astronomer.io/requests/ee38ece4-b57a-11ee-8e69-42004e494300

We ingested CLI docs and I tried out asking about how to read airflow logs. Seems to be working. Closing the issue
