### ISSUE TITLE
Ingest should not run during weaviate backup window

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#105]
https://github.com/astronomer/ask-astro/blob/c45487c7f12a9424dbe885580c687e35e30b7de4/airflow/dags/ingestion/ask-astro-load.py#L52

Ingest sometimes fails if it occurs during a weaviate backup window (midnight UTC).  Better to set ingest for `0 5 * * *`

**Comment by sunank200** [comment]
We currently don't backup in current approach

**Comment by davidgxue** [comment]
Closing this issue as it is not relevant.
