### ISSUE TITLE
Change bulk schedule to none

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#114]
https://github.com/astronomer/ask-astro/blob/c45487c7f12a9424dbe885580c687e35e30b7de4/airflow/dags/ingestion/ask-astro-load.py#L52-L55

https://github.com/astronomer/ask-astro/commit/b8c206f1805005ac5733547caa5e486718e546bd changed the schedule interval but the original intention was for this bulk DAG to only be used for initial load.  Nightly ingest should run from individual DAGs.

**Comment by Lee-W** [comment]
I believe it's already been changed to None https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load.py#L59. Close this one
