### ISSUE TITLE
Github tasks can run in parallel

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#115]
https://github.com/astronomer/ask-astro/blob/c45487c7f12a9424dbe885580c687e35e30b7de4/airflow/dags/ingestion/ask-astro-load.py#L253-L262

After switching Airflow docs ingest to HTML it is no longer necessary to ingest github tasks in parallel for API rate limits.

**Comment by Lee-W** [comment]
I am not sure whether I understand correctly, but according to the title, it looks like we want to run the GitHub tasks in parallel which seems to be [there](https://github.com/astronomer/ask-astro/blob/main/airflow/dags/ingestion/ask-astro-load.py#L289) already. Closing this one. Please reopen it if I misunderstand it.
