### ISSUE TITLE
Add Astro Forum docs

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#120]
**Please describe the feature you'd like to see**
Request from Steven to add https://forum.astronomer.io/ as a data source.

**Describe the solution you'd like**
Add forum docs for ingest.  Some older posts are inaccurate so a "recent" (ie. last 2 years) cutoff date will be needed.   Also we would want to check tags for "software" and decide whether we want to ingest those.

**Are there any alternatives to this feature?**
No

**Additional context**
Forum is powered by Discourse. https://meta.discourse.org/t/does-discourse-support-export-conversations-as-an-organized-bulk-of-data/180537

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by phanikumv** [comment]
PR being reviewed
