### ISSUE TITLE
Astro docs should link to the webpage not github

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#129]
**Please describe the feature you'd like to see**
Currently the ingest for astro docs and astro learn uses github markdown pages.  The docLink points to the github page. 

**Describe the solution you'd like**
 It would be nice to have this point at the docs.astronomer.io webpage.

**Are there any alternatives to this feature?**
Current ingest is okay for RAG performance.

**Additional context**
Can look at converting the docLink but this may not be deterministic.  Also the markdown extract needs to be repo/dir-agnostic so likely can't specify logic to convert.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
Issues with broken URL for astro docs. Debugging this currently.

**Comment by sunank200** [comment]
[PR](https://github.com/astronomer/ask-astro/pull/238)
