### ISSUE TITLE
Create test plan for Ask-Astro phase 2

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#142]
- Create a test plan for Ask-Astro phase 2
- Run the tests based on following and post the results with airflow docs ingested

> - Is there good data in the database? —> Use Weaviate client directly or streamlit app
> - Is the frontend retrieving it properly? → The current approach is fine where we as questions to slack directly
> 
> Scenarios
> ------------
> - both are positive
> - both negative → problem with documents we are embedding or ingestion  —> log issue for this
> - DB is good but not front end → problem with conversation retrival ??????? —> log issue for this
> - Frontend is good but DB is bad →  log a bug
> 
> 70% positive - good enough for us to go ahead.
> 
> - % for postive response
> - % with postive result in top 3 document sources
> - Average of both
> 
> More relevant questions from langsmith - with correctness check (bad and good answers)

**Comment by mpgreg** [comment]
Test pipeline for this is at https://github.com/mpgreg/ask-astro/blob/add_baseline_test/airflow/dags/monitor/test_baseline.py
with test logic at https://github.com/mpgreg/ask-astro/blob/add_baseline_test/airflow/include/tasks/utils/retrieval_tests.py

**Comment by vatsrahul1001** [comment]
Latest Test results : https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1200545478

**Comment by sunank200** [comment]
This can be closed right @vatsrahul1001 ?

**Comment by vatsrahul1001** [comment]
[summary](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1544700686&fvid=583920677)
Total Test Cases: 52
Passed Test Cases: 45
Failed Test Cases: 7

More [context](https://astronomer.slack.com/archives/C066Y5NTJG0/p1700730162307669)
