### ISSUE TITLE
Automate the test plan to run via script based on test plan

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#143]
Currently, the test plan is being run manually and evaluated. 
- Automate running test plan via script as manually running it is error-prone.
- Run the script to answer questions from APIs.
- Run the script to retrieve the answers directly from Weaviate.
- Populate the results to the cloud bucket for evaluation.
- Evaluation is manual currently 

Depends on: #142

**Comment by sunank200** [comment]
@mpgreg can you link this issue to the PR you have created? @vatsrahul1001 can add more details as required, please?

**Comment by mpgreg** [comment]
Some feedback.  
- Should consider NOT providing 'answer' to vectordb search.  The point of the search is to see which links are retrieved. This will save cost too.  Use `near_text` instead of `with_ask`.
- Remove duplicates from references.

**Comment by sunank200** [comment]
@vatsrahul1001 @mpgreg can you create the PR for this, please?

**Comment by vatsrahul1001** [comment]
@sunank200 as discussed this should not be part of be 28th release, also @mpgreg can you raise the PR of your script whenever you have bandwidth afterwards we can close this

**Comment by phanikumv** [comment]
Waiting for @mpgreg to create the PR with the script that he developed

**Comment by vatsrahul1001** [comment]
@mpgreg we need to plan this out, let us know if there is any update on this?

**Comment by phanikumv** [comment]
Waiting for an ETA on this @mpgreg

**Comment by sunank200** [comment]
@mpgreg This is super important for testing phase 2.5 changes. Any update on this?

**Comment by phanikumv** [comment]
@mpgreg can you link the PR to this issue please?
