### ISSUE TITLE
Test and evaluate the result for ingested data from Airflow docs with tokenization as lowercase

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#144]
After the data is ingested along with airflow docs with tokenization as `lowercase` we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results.

Depends on: #145

**Comment by vatsrahul1001** [comment]
This is not Priority for @28th release as discussed with @sunank200 , we can work on this post release
