### ISSUE TITLE
Change the langchain code for Hybrid search

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#147]
As the response for Ask-Astro is off for certain responses as described in #133 

We should try the following:
- increase the number of documents we retrieve per rewording
- when joining the docs together, we should rerank using something like [cohere reranker](https://python.langchain.com/docs/integrations/retrievers/cohere-reranker)
- it seems like the documents are all in weaviate properly, so it feels like a problem with how we do document retrieval. We could also try hybrid search[https://python.langchain.com/docs/integrations/retrievers/weaviate-hybrid](https://python.langchain.com/docs/integrations/retrievers/weaviate-hybrid)

**Comment by phanikumv** [comment]
PR has been created for this.

**Comment by Lee-W** [comment]
As we've been testing with this, and doesn't seem to work, should we close this one and related PRs?

**Comment by sunank200** [comment]
Yes we should close this as it won't go in for Nov 28th release @Lee-W

**Comment by phanikumv** [comment]
what about the first two tasks?

- increase the number of documents we retrieve per rewording
- when joining the docs together, we should rerank using something like [cohere reranker](https://python.langchain.com/docs/integrations/retrievers/cohere-reranker)

**Comment by sunank200** [comment]
> - increase the number of documents we retrieve per rewording
> - when joining the docs together, we should rerank using something like [cohere reranker](https://python.langchain.com/docs/integrations/retrievers/cohere-reranker)

Both are done in this [#170](https://github.com/astronomer/ask-astro/pull/170)
