### ISSUE TITLE
Test and evaluate the Ask-Astro after hybrid search

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#148]
Test and evaluate the Ask-Astro results after following:
- hybrid search
- increase the number of documents we retrieve per rewording to 5
- when joining the docs together, we should rerank using something like [cohere reranker](https://python.langchain.com/docs/integrations/retrievers/cohere-reranker)

Depends on: #147

**Comment by vatsrahul1001** [comment]
Results after [hybrid search](https://github.com/astronomer/ask-astro/issues/148#top) implementation
Total test - 27
Pass - 13
Fail - 14

As per results responses are very inconsistent and for the same questions opposite answer

Raised below issues
1. https://github.com/astronomer/ask-astro/issues/167
2. https://github.com/astronomer/ask-astro/issues/168
3. https://github.com/astronomer/ask-astro/issues/169

**Comment by sunank200** [comment]
Conclusion from testing by @vatsrahul1001 @pankajkoti :
1. We should consider rolling back the hybrid approach as both the sources and responses have degraded in quality
The [results](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1200545478) are in the link.
Hence, rolling back the deployment to the state with airflow docs.
