### ISSUE TITLE
Need to consolidate to a single HTML ingest

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#164]
**Please describe the feature you'd like to see**
Multiple extract functions use almost identical HTML extract logic.  

**Describe the solution you'd like**
Should consolidate to a single function if possible and use dynamic task mapping like github extract.

**Are there any alternatives to this feature?**

**Additional context**

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
Discussed with @pankajastro - a single HTML extractor makes sense.

**Comment by pankajastro** [comment]
just adding more here a single extractor makes sense but we require a think layer over it for the different sources because we need some different cleanup approaches for different sources for example in atstro sdk I'm excluding if docs url has ```"autoapi", "genindex.html", "py-modindex.html", ".md", ".py"``` but for provider excluding ``` "_api", "_modules", "_sources", "changelog.html", "genindex.html", "py-modindex.html", "#"```. **So at least different task per source makes sense to me** and if we keep a different dag per source then maybe it will be easy to run i.e we can upsert only source we want

**Comment by phanikumv** [comment]
Created draft PR on this one

**Comment by pankajastro** [comment]
just marked PR as ready for review, would appreciate a review
