### ISSUE TITLE
Consider ingest of astro sdk docs

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#165]
**Please describe the feature you'd like to see**
Astro sdk is referenced in docs.astronomer.io (which we ingest) but not always accurate.  Should ingest astro sdk specific docs.

**Describe the solution you'd like**
Can probably use consolidated HTML ingest with https://astro-sdk-python.readthedocs.io/en/stable/

**Are there any alternatives to this feature?**

**Additional context**

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged
