### ISSUE TITLE
Consider ingesting astronomer-providers docs

### ISSUE THREAD

**Issue by mpgreg** [astronomer/ask-astro#166]
**Please describe the feature you'd like to see**
Astro providers are referenced several times in docs that we ingest today (docs.astronomer.io) but some context is missing.

**Describe the solution you'd like**
Can probably ingest with consolidated html extract from https://astronomer-providers.readthedocs.io/en/stable/

**Are there any alternatives to this feature?**

**Additional context**

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors

**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by sunank200** [comment]
**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged
