### ISSUE TITLE
Ask Astro bot || Failure in responding the results || getting connection error with Weaviate

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#167]
Getting connection error with Weaviate

Langsmith Trace - [https://smith.langchain.com/o/4942ae8b-e5be-4964-bb1f-7544886fa06d/projects/p/5d1aeb88[…]6%3A59.451Z%22%7D&peek=0533b6b0-b0f3-433b-b79d-53d66946af45](https://smith.langchain.com/o/4942ae8b-e5be-4964-bb1f-7544886fa06d/projects/p/5d1aeb88-dc89-4f37-9e7c-3f5a3cf973e2?timeModel=%7B%22start_time%22%3A%222023-11-18T11%3A16%3A59.451Z%22%7D&peek=0533b6b0-b0f3-433b-b79d-53d66946af45)

Slack [Thread](https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1700564691527969)
<img width="503" alt="image" src="https://github.com/astronomer/ask-astro/assets/43964496/6e4bfa94-6db9-4766-9101-b06419348569">

**Comment by mpgreg** [comment]
I was having availability issues with langsmith yesterday.  This could be related.
