### ISSUE TITLE
Code samples from Learn Docs are shown as sources with a non-existent link

### ISSUE THREAD

**Issue by TJaniF** [astronomer/ask-astro#17]
When Ask Astro shows a Source that is from the code-samples folder (retrieved from `https://github.com/astronomer/docs/blob/main/code-samples/dags`) in the Astronomer Docs repo it shows a link to the docs.astronomer page like this `https://docs.astronomer.io/code-samples/dags/...`. These code samples are embedded in other docs on the page and not accessible through that link. 

Solution proposed in #16 : 
create an extra case for the URL prefix and link to the DAG code in the GitHub repo.

**Comment by shillion** [comment]
I think this is now fixed ([example](https://ask.astronomer.io/requests/2e634dee-b4ce-11ee-8e69-42004e494300)) by other changes to the way we ingest DAGs.

**Comment by TJaniF** [comment]
Yes, it is @shillion #238 fixed it, apologies I closed the PR #16 but forgot to close the issue 😅
