### ISSUE TITLE
Test and evaluate the quality of response after single HTML ingestion

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#187]
After the data is ingested along with single HTML ingestion we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results.

Depends on: #164

**Comment by vatsrahul1001** [comment]
tested this only observation was that source count has increased, however, as discussed with @sunank200 this was related to https://github.com/astronomer/ask-astro/pull/247, we should be ok to close this

[Results](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1992460551)
