### ISSUE TITLE
Test and evaluate the quality of response after using new Weaviate providers after release of 1.3.0

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#189]
After replacing taskflow API with the OSS weaviate hook we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results.

Depends on: #136

**Comment by sunank200** [comment]
@vatsrahul1001 you can test the change as the latest ingestion with new weaviate provider is done for dev stackbot as per [246](https://github.com/astronomer/ask-astro/pull/246)

**Comment by vatsrahul1001** [comment]
Verified this LGTM, and I do not see any regression in sources and response

[Results](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1143451957)
