### ISSUE TITLE
Ingest Astro CLI docs

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#190]
**Please describe the feature you'd like to see**
Currently the ingest for astro docs and astro learn uses github markdown pages.  The docLink points to the github page. 
Ingest the astro cli  docs to Ask-Astro from [astro-cli docs](https://docs.astronomer.io/astro/cli/overview)

**Describe the solution you'd like**
Ingest the astro cli  docs to Ask-Astro from [astro-cli docs](https://docs.astronomer.io/astro/cli/overview)

**Are there any alternatives to this feature?**
Current ingest is okay for RAG performance.

**Additional context**

Ingest the astro cli  docs to Ask-Astro from [astro-cli docs](https://docs.astronomer.io/astro/cli/overview)
**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Note:**
- [ ] After the implementation is complete, the data should be ingested to the dev database and the dev slackbot should be deployed.
- [ ] This change should be tested by @vatsrahul1001 and after his take on quality of response, this should be merged

**Comment by Lee-W** [comment]
@vatsrahul1001 I've tested and deployed to dev. Could you please test it when you're available? Thanks!
