### ISSUE TITLE
Test and evaluate the quality of response after ingestion of astro cli docs

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#191]
After ingestion of astro cli docs we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results.

Depends on: #190

**Comment by sunank200** [comment]
Also this can be tested: [#164](https://github.com/astronomer/ask-astro/issues/164)

**Comment by vatsrahul1001** [comment]
I have tested the Astro CLI, and its responses have improved. Additionally, sources from Astro CLI ingested docs are now evident. Overall, everything looks good; however, I have observed that Astro CLI docs are starting to appear in some Astro SDK and Astronomer Providers sources."
