### ISSUE TITLE
Test and evaluate the quality of response after change of github issue extract to get all issues not only open

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#193]
After the change of github issues issues extract to get all issues not only open issues,  we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results.

Depends on: #113

**Comment by vatsrahul1001** [comment]
Verified this, closing this, [results](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=380133848)
