### ISSUE TITLE
Test and evaluate the quality of response after ingestion of stackoverflow APIs

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#194]
After ingestion using stackoverflow APIs we need to run the same [test plan](https://www.notion.so/astronomerio/Ask-Astro-questionnaire-4dfa9e4c55514ec48a83dda2be4e55d2) again and evaluate the results. 

Depends on: #126

**Comment by sunank200** [comment]
This has to be separate

**Comment by vatsrahul1001** [comment]
verified this I do not see any regression 

[Results](https://docs.google.com/spreadsheets/d/13cVqNikix82YjCPA4t0XaULg3XccBnvrQUmQa9VwgC0/edit#gid=1774205753)
