### ISSUE TITLE
Migrate to Azure Open AI  and Open AI dedicated account for Ask-Astro

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#197]
Currently, we use a CSE dev account for Azure Open AI. And Open AI API key is not dedicated for Ask-Astro.

- [x] Create IT ticket for dedicated Azure Open AI and get permission from Microsoft Open AI
- [ ] Get access to separate prod and dev Open AI key for Ask-Astro
- [ ] Deploy the dev and prod with the above keys

**Comment by phanikumv** [comment]
ETA:20-Dec

**Comment by sunank200** [comment]
Look into Microsoft Azure Open AI for GPT-4

**Comment by sunank200** [comment]
I have already requested GPT-4 and request Azure CSM for the same. More [here](https://astronomer.slack.com/archives/C03GCRRDT1Q/p1703174495009029). IT ticket is [here](https://galileo.astronomer.io/support/tickets/7664)

**Comment by phanikumv** [comment]
Changed target date as we are stuck on the IT requests

**Comment by sunank200** [comment]
Blocked on the following IT issues:
- https://galileo.astronomer.io/support/tickets/7709
- https://galileo.astronomer.io/support/tickets/7708
Tried multiple times to resolve this with IT and Microsoft [here](https://astronomer.slack.com/archives/C03GCRRDT1Q/p1704730908452309?thread_ts=1703174495.009029&cid=C03GCRRDT1Q) But no progress as of now. Have informed the same to Steven and team.

**Comment by sunank200** [comment]
This issue is still open and blocked on IT so removing it from this release as this is not a blocker issue

**Comment by davidgxue** [comment]
Testing the new API keys in dev environment today. There are still 2 minor things I want to close out/confirm with Microsoft Azure folks before I fully conclude this is working. ETA end of this week at the latest!

**Comment by davidgxue** [comment]
@sunank200 Is this ticket also for OpenAI? I only see progress report and tickets related to Azure migration. What was the status for the OpenAI accounts? cc @shillion

**Comment by davidgxue** [comment]
This should be now considered complete. We do not plan to consolidate the OpenAI account and the Azure OpenAI account now is all under one subscription.
