### ISSUE TITLE
DAG to delete the message deleted from slack

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#20]
There should be a slack DAG which deletes the message removed from the slack

**Comment by mpgreg** [comment]
In thinking about this I think the upsert logic should take care of it.  If messages are deleted in slack or the slack archive then the UUID in ingest will hash to a new value and trigger an upsert.

**Comment by mpgreg** [comment]
Actually the upsert will only update messages if a user replies to a thread.  For the base message we still need logic to remove.

**Comment by shillion** [comment]
We're not ingesting from Slack, so this can be closed/deleted.
