### ISSUE TITLE
Change Ingestion for Astro SDK Doc to Only Ingest the Latest Version

### ISSUE THREAD

**Issue by pankajastro** [astronomer/ask-astro#209]
currently, we extract all versions of astro-sdk docs but we should only ingest the latest (e.g. version 0.33 at the moment, instead of also ingesting version 0.31 docs). We should change the logic to extract only the latest https://github.com/astronomer/ask-astro/pull/199

**Comment by davidgxue** [comment]
#293 resolves this issue
