### ISSUE TITLE
Improve quality of responses 

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#213]
I am compiling a list of Slack links for all the failure responses. We should investigate these and work on improving the quality of our responses.

https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888708418929
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888719400219
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702895252358599
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888720058339
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888722872869
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888723560539
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888725241529
https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702888726261829

**Comment by vatsrahul1001** [comment]
After the ingestion of Astro Forum docs  (https://github.com/astronomer/ask-astro/pull/212), I observed that in certain responses, sources are cited from forum docs that lack any corresponding response. Additionally, it seems that the document may not be closely related, and the inclusion of the forum source appears to be a result of a word match in the question asked.


<google-sheets-html-origin><style type="text/css"></style>
question | Status | crc_answer | Comments
-- | -- | -- | --
I want to create a task dynamically does airflow support it? | Pass | https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702990644128149 | I see forum doc as first source which does has dynamic task in title, however, there was no discussion around dynamic mapping in there.Forum link: https://forum.astronomer.io/t/dynamic-tasks-based-on-runtime-config/1770
How can I extract airflow dag run information? Such as start_date, run_id? | Pass | https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702990649814709 | Forum doc with only question and not responsesForum link:https://forum.astronomer.io/t/can-airflow-tracks-each-dag-run-based-on-parameter-passed-into-it/1861
I'm using EcsRunTaskOperator in Airflow 2.5.1, how can I wait until the ECS task is finished? | Pass | https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702990653835769 | Forum link : https://forum.astronomer.io/t/run-next-task-group-if-the-same-task-group-from-previous-dag-run-finished/2546 showing not related to EcsRunTaskOperator, however , releated to task finished
What is the best way to skip tasks based on a condition given in the parameters of the dag? | Pass | https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702990655367769 | Forum link: https://forum.astronomer.io/t/can-airflow-tracks-each-dag-run-based-on-parameter-passed-into-it/1861 looks like not related
list all extras of astronomer-providers? | Fail | https://ankit-test-group.slack.com/archives/C061F4LR4KT/p1702993436719699 | Not related Forum Link: https://forum.astronomer.io/t/invoice-option-for-astronomer-certification-bundles/2414

**Comment by davidgxue** [comment]
Closing this issue as it is duplicate/covered by another issue https://github.com/astronomer/ask-astro/issues/133
