### ISSUE TITLE
Improve readability of list results

### ISSUE THREAD

**Issue by dpatlut** [astronomer/ask-astro#215]
**Describe the bug**
When a list is returned by Ask Astro, it is poorly formated.

**To Reproduce**
1. Run Ask-Astro website
2. Ask it to give a list of anything
3. See output

**Expected behavior**
A list with line breaks between each list item

**Screenshots**
<img width="1115" alt="Screen Shot 2023-12-18 at 11 05 47 AM" src="https://github.com/astronomer/ask-astro/assets/8918666/84bc50e8-5409-40fa-bbea-ff271e4eb521">
![Screen Shot 2023-12-15 at 11 51 09 AM](https://github.com/astronomer/ask-astro/assets/8918666/ac319bd2-a017-4389-89c1-2d234ec3d182)

**Additional context**
N/A

**Comment by pankajkoti** [comment]
Closed as work was completed in PR #240
