### ISSUE TITLE
Error in extract forum docs in local

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#228]
**Describe the bug**

I was trying to ingest forum docs local in bulk load DAF and I am getting the following error. It missed here. https://github.com/astronomer/ask-astro/pull/212 This error is coming as part of bulk load DAG.

**Error log**
[dag_id=ask_astro_load_bulk_run_id=manual__2023-12-20T16_14_25.623793+00_00_task_id=extract_astro_forum_doc_attempt=2 (1).log](https://github.com/astronomer/ask-astro/files/13740633/dag_id.ask_astro_load_bulk_run_id.manual__2023-12-20T16_14_25.623793%2B00_00_task_id.extract_astro_forum_doc_attempt.2.1.log)

**Comment by pankajastro** [comment]
I ran it on Astro dev cluster and worked fine. you can details here https://clmkpsyfc000301kcjie00t1l.astronomer.run/dahdhb9e/dags/ask_astro_load_bulk/grid

**Comment by pankajkoti** [comment]
@sunank200 I have unassigned myself from this one as discussed in the standup

**Comment by Lee-W** [comment]
I just finished testing it locally, and it works as expected. Since both @pankajastro and I can no longer reproduce it. Will close it for now
