### ISSUE TITLE
Send alerts for Ask Astro DAG failures to Slack channel

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#231]
**Describe the bug**

Looks like currently we do not have any alerts set for Ask Astro Ingestion & Monitor DAGs when they fail. 

**Expected behavior**

The errors should be posted for failures to ask-astro-alert Slack channel in Astronomer Slack workspace.

**Comment by pankajastro** [comment]
Look like production does not have latest dag

**Comment by pankajastro** [comment]
https://github.com/astronomer/ask-astro/pull/225 should fix it

**Comment by Lee-W** [comment]
> This [DAG](https://clmkpsyfc000301kcjie00t1l.astronomer.run/d2uulcqu/dags/ask_astro_load_airflow_docs/grid) fails. Debugging is required

not yet been able to reproduce the same issue on my deployment yet

**Comment by Lee-W** [comment]
as discussed with Ankit earlier, I should no longer work on this one but work on https://github.com/astronomer/ask-astro/issues/196 instead. unassign myself

**Comment by sunank200** [comment]
@Lee-W you can do this after #196 is done. But why is this failing in prod?

**Comment by pankajkoti** [comment]
@sunank200 which ones are ingestion DAGs and which ones are monitoring DAGs?

**Comment by pankajastro** [comment]
> @sunank200 which ones are ingestion DAGs and which ones are monitoring DAGs?

ingestion dag: https://github.com/astronomer/ask-astro/tree/main/airflow/dags/ingestion
monitoring dag: https://github.com/astronomer/ask-astro/tree/main/airflow/dags/monitor
