### ISSUE TITLE
Slack bot returning source documents in different order from backend/website/LangSmith

### ISSUE THREAD

**Issue by davidgxue** [astronomer/ask-astro#250]
**Describe the bug**
The Ask Astro Slack bot is returning related documents in a different order from that of backend or on the ask astro website or the one on LangSmith. This is occuring on the dev server.

**To Reproduce**
1. Redeploy cloud build ask-astro-dev-00289-s58 and serve 100% traffic there for the dev server
2. Go to the dev server's front end website, in my case https://hybrid-search-reword-and-rer.ask-astro.pages.dev/requests/097dca16-ab93-11ee-82fc-42004e494300, then send a question "What is the Astro SDK?"
3. See results and related documents returned
![image](https://github.com/astronomer/ask-astro/assets/26350341/c9128154-260f-4d78-88b5-80d0e8f83616)

4. Go to Ask Astro's slack bot channel and ask the same question "What is the Astro SDK?"
![image](https://github.com/astronomer/ask-astro/assets/26350341/39329c18-8f62-4c44-803f-80524879ae1d)
5. See the the related documents returned are ordered differently. The first document on the website is https://docs.astronomer.io/learn/astro-python-sdk-etl, but the first document returned from the slack bot is https://astro-sdk-python.readthedocs.io/en/stable/aep/README.html.
6. Checking on LangSmith, the ordering of documents on the website/backend is correct, but the ordering from slack is different. See link here https://smith.langchain.com/public/66cee2ee-507c-480b-bd8f-3098ea93833a/r.

**Expected behavior**
The slack bot's related documents returned should be the exact same ordering as the ones from backend/website and on LangSmith.

**Comment by pankajkoti** [comment]
@sunank200 I have other assignments as per Sprint planning. Assigned it to you
