### ISSUE TITLE
ask_astro_load_astro_forum DAGs failing intermittently

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#262]
**Describe the bug**

While running ask_astro_load_astro_forum DAG, it fails intermittently with following error:
[dag_id=ask_astro_load_astro_forum_run_id=manual__2024-01-11T08_59_30.274127+00_00_task_id=get_astro_forum_content_attempt=4.log](https://github.com/astronomer/ask-astro/files/13900951/dag_id.ask_astro_load_astro_forum_run_id.manual__2024-01-11T08_59_30.274127%2B00_00_task_id.get_astro_forum_content_attempt.4.log)

DAG runs: [here](https://clmkpsyfc000301kcjie00t1l.astronomer.run/d2gj0n9c/dags/ask_astro_load_astro_forum/grid?dag_run_id=manual__2024-01-11T08%3A59%3A30.274127%2B00%3A00&task_id=get_astro_forum_content&tab=logs)

**Expected behavior**

The DAG should run fine.

**Comment by sunank200** [comment]
@pankajastro it failed [here](https://clmkpsyfc000301kcjie00t1l.astronomer.run/d2gj0n9c/dags/ask_astro_load_bulk/grid?dag_run_id=manual__2024-01-11T08%3A59%3A50.254593%2B00%3A00&task_id=extract_astro_forum_doc&tab=logs) as well

**Comment by phanikumv** [comment]
Unable to reproduce it as discussed in the sprint call

**Comment by davidgxue** [comment]
I am consistently getting this in my local env. I think this is failing at this line https://github.com/astronomer/ask-astro/blob/28f1de808edfe66d5c23ac30c406dbbbaca4d8d9/airflow/include/tasks/extract/utils/html_utils.py#L38. And after some investigation by printing out the response content, I believe the forum website rate limits the web scrapper after a few requests. We are getting a 429 response from all requests leading to an empty DF.
![image](https://github.com/astronomer/ask-astro/assets/26350341/0938615a-ea51-4bdb-acd9-331ddb43646c)

I added a user agent in the requests.get code and added time.sleep for 2 seconds at a few spots, it seems to have fixed the issue locally for me. Should I raise a PR for this?

@sunank200  @phanikumv
