### ISSUE TITLE
Add Metric to Track Usage Source (Slack Bot vs Webapp)

### ISSUE THREAD

**Issue by davidgxue** [astronomer/ask-astro#275]
**Please describe the feature you'd like to see**
Add Metric to Track Usage Source (Slack Bot vs Webapp)

**Describe the solution you'd like**
Add metric tracking so that we can see how many/what proportion of requests are from slack app vs webapp, and specifically be able to trace individual requests to see which one is from where

**Are there any alternatives to this feature?**
Perhaps we can also track specifically which slack server this is used, or other details that maybe useful.

**Comment by venkatajagannath** [comment]
@davidgxue @shillion 

Are there any other metrics that might be useful?

I'm working on a different issue which will require an update to the request object and possibly the front end code too. 

If there is any other information we would like, I can update the request object with those fields too.
