### ISSUE TITLE
Migrate the ask-astro project to new GCP account

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#29]
- [x] Migrate the Firestore.
- [x] Create separate dev and prod cloud build.
- [x] Add cloud build and cloud run for new account.
- [x] Integrate both deployments to cloud flare.
- [x] Run prod with new GCP account and dev with CSE -dev account

**Comment by pankajastro** [comment]
@sunank200 do we need anything more for this issue?

**Comment by sunank200** [comment]
This is done. Just the PR needs to be merged.

**Comment by sunank200** [comment]
PRs: [https://github.com/astronomer/ask-astro/pull/48](https://github.com/astronomer/ask-astro/pull/48), [https://github.com/astronomer/ask-astro/pull/46](https://github.com/astronomer/ask-astro/pull/46), [https://github.com/astronomer/ask-astro/pull/42](https://github.com/astronomer/ask-astro/pull/42)
