### ISSUE TITLE
Setup and run Ask-Astro end to end

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#32]
- [x] Setup and run Ask Astro end to end using local dev story.
- [x] Use ngrok to build slack locally.
- [x] Create a personal Slack bot and run Ask-Astro.
- [x] Please outline the changes required to the slack bot for the Ask Astro channel on OSS airflow and create corresponding smaller issues if needed.

**Comment by Lee-W** [comment]
As we already have an ask-astro slack bot ready, the only thing required is asking one who has the permission to add the app
