### ISSUE TITLE
Integrate with airflow-astronomer channel in airflow slack

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#37]
- [ ] Integrate with airflow-astronomer channel in airflow slack

**Comment by Lee-W** [comment]
As discussed with @sunank200 earlier, the last step for this ticket is to get permission to add the bot into oss airflow slack #airflow-astronomer. We're now waiting for @sunank200 final confirmation to proceeded

**Comment by Lee-W** [comment]
@sunank200 Please let me know whether you get the confirmation for us to process so that we can reach out to OSS airflow slack admin. Thanks!

**Comment by Lee-W** [comment]
As synced with @sunank200 and the bot is on airflow-astronomer now, I think we can close this one
