### ISSUE TITLE
Run the ask astro chat end to end on a private slack account after migration to new GCP account.

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#38]
- [x] Run the ask astro chat end to end on a private slack account after migration to new GCP account
- [x] Integrate with new slack channel(or Astronomer AskAstro channel) from new GCP account
- [x] Documentation for someone to run it end-to-end

**Comment by Lee-W** [comment]
As discussed yesterday, I'll wait for ask-astro backend with the new GCP account setup and test this one

**Comment by sunank200** [comment]
I have tested this with the documentation changes: https://github.com/astronomer/ask-astro/pull/42

I have created a Slack bot on a private Slack account and used a new GCP account and it works fine. Adding the screenshots:

<img width="1718" alt="Screenshot 2023-10-19 at 6 28 29 PM" src="https://github.com/astronomer/ask-astro/assets/8670962/c389b976-9f6d-4807-aee2-f0583813c4a8">
<img width="937" alt="Screenshot 2023-10-19 at 6 28 51 PM" src="https://github.com/astronomer/ask-astro/assets/8670962/c959f049-77ff-458e-bb9e-d9ce4e6a0228">

**Comment by Lee-W** [comment]
I've just checked that all the action item has been done. Do you think we should close this one? Or is there anything we need to do or check for this one?

**Comment by sunank200** [comment]
No I think this looks good @Lee-W

**Comment by sunank200** [comment]
PR: [https://github.com/astronomer/ask-astro/pull/42](https://github.com/astronomer/ask-astro/pull/42)
