### ISSUE TITLE
User testing for the existing Slack bot implementation

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#41]
Currently, we have not done user testing for the current Slack bot implementation. This is critical before the release of Phase - 2.
- [ ] User testing for Slack bot 
    - [ ] Identify the issues and bugs with the workflow.
    - [ ] Create the issue with a proper description.
    - [ ] Create a test plan.
    - [ ] Coordinate with Steven and @pgagnon for this and create required issues on ask-astro GitHub repo.

**Comment by sunank200** [comment]
[Test plan](https://astronomer.slack.com/archives/C05QJA9LTR9/p1699272568218509) created by @vatsrahul1001

**Comment by sunank200** [comment]
@vatsrahul1001 is creating issues in the GitHub repo

**Comment by phanikumv** [comment]
@vatsrahul1001 Can you link all the issues observed to this ticket?

**Comment by vatsrahul1001** [comment]
1. https://github.com/astronomer/ask-astro/issues/82
2. https://github.com/astronomer/ask-astro/issues/101
3. https://github.com/astronomer/ask-astro/issues/83
4. https://github.com/astronomer/ask-astro/issues/100

**Comment by vatsrahul1001** [comment]
I have done testing and execution status is updated 7cf60d17a16925a461e4855c27e53265c06cf150
