### ISSUE TITLE
Separate the weaviate and DAGS for dev to prod account

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#44]
- [ ] Separate the prod and dev for ingestion and feedback DAGs.
- [ ] Work on running ingestion and feedback DAGs with weaviate in dev.
- [ ] Change the credentials in prod and dev for cloud build accordingly.
- [ ] Migrate older prod to new weaviate account. Make older dev as dev database and new account as prod database

**Comment by pankajastro** [comment]
> Separate the prod and dev for ingestion and feedback DAGs.

Are we going to keep this dag in the same astro instance?

> Migrate older prod to new weaviate account. Make older dev as dev database and new account as prod database

I login to https://console.weaviate.cloud/dashboard we already have a cluster so do need a new cluster for prod or we will use the same but a different database?

@sunank200 we need to discuss these points

**Comment by sunank200** [comment]
We already have two separate deployments DAGs for prod and dev: [https://cloud.astronomer.io/clmkpupdk000401lpj28teo2t/deployments](https://cloud.astronomer.io/clmkpupdk000401lpj28teo2t/deployments)

There are two clusters for prod and dev already for weaviate. I have DMed you the creds.

**Comment by pankajastro** [comment]
We have created 2 deployment ask-astro-prod-phase-2 and ask-astro-dev-phase-2 (we will rename it later). 
Created 2 weaviate schemas DocsDev and DocsProd and ingested data in them and tested with slack bot

**Comment by sunank200** [comment]
The URLs for the deployment can be found in connection details in the following deployments: We already have two separate deployments DAGs for prod and dev: [https://cloud.astronomer.io/clmkpupdk000401lpj28teo2t/deployments](https://cloud.astronomer.io/clmkpupdk000401lpj28teo2t/deployments)

**Comment by sunank200** [comment]
@pankajastro we need to add a schedule to run the prod DAGs on daily basis. For dev it can be manual run.

**Comment by sunank200** [comment]
We should run the `ask-astro-load` DAG without slack ingestion.
