### ISSUE TITLE
Implement some observability/monitoring part-2

### ISSUE THREAD

**Issue by pankajastro** [astronomer/ask-astro#59]
As part of our observability and monitoring effort, we want to set up the monitoring for the following components apart from this [issue](https://github.com/astronomer/ask-astro/issues/39):

- Explore and set up the monitoring for backend APIs. This should ping the APIs every 5 minutes and post a notification on Slack if the APIs are down with a relevant response.
- Slack bot monitoring
- Page on GitHub on what kind of observation metrics/actions are needed.

More details around this can be found [https://github.com/astronomer/ask-astro/issues/39#issuecomment-1782573622](https://github.com/astronomer/ask-astro/issues/39#issuecomment-1782573622)

**Comment by sunank200** [comment]
Created a postman collection to monitor the APIs: [postman collection](https://universal-water-710753.postman.co/workspace/ask-astro~ce4cea4d-b986-4e21-910b-dd75df5b7cbd/collection/20192861-e5a396fd-4bdc-4201-bc57-9be263373e0e?action=share&creator=20192861)

**Comment by sunank200** [comment]
Working on making this part of monitoring DAG instead

**Comment by phanikumv** [comment]
PR will be created today
