### ISSUE TITLE
Document sources are wrong in the answers

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#80]
The answers from the Slackbot return the sources and these sources are wrong most of the time and are very irrelevant.

More details here: [https://astronomer.slack.com/archives/C05QJA9LTR9/p1698954492896499](https://astronomer.slack.com/archives/C05QJA9LTR9/p1698954492896499)

For example: this message on [slack](https://apache-airflow.slack.com/archives/C03T0AVNA6A/p1699020674361439) has query hello and it is returning various sources

**Comment by shillion** [comment]
Good example [here](https://apache-airflow.slack.com/archives/C03T0AVNA6A/p1699018403187419)
The sources referenced seem much less relevant than (say) the [Airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html).

**Comment by vatsrahul1001** [comment]
@shillion correct sources/Related docs are not relevant sometimes

**Comment by phanikumv** [comment]
Might disable this feature if not fixed in time for the Nov 15 release, being discussed [here](https://astronomer.slack.com/archives/C05QJA9LTR9/p1698954492896499)

**Comment by sunank200** [comment]
We tried ingested airflow docs which has improved the reference sources.

**Comment by sunank200** [comment]
We also tried [Hybrid search with Cohere re-ranking](https://github.com/astronomer/ask-astro/pull/170). This did not work well and answers as well as sources degraded. We will be continuing on this after Nov 28th release

**Comment by phanikumv** [comment]
David will be working on this, as discussed in the sprint planning call

**Comment by phanikumv** [comment]
@davidgxue are we making progress on this ticket?

cc @shillion @kaxil

**Comment by davidgxue** [comment]
Closing this issue as it is duplicate/covered by another issue https://github.com/astronomer/ask-astro/issues/133
