### ISSUE TITLE
Ask Astro web: History of previous query and response are getting overridden by original query and response

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#83]
While testing from https://ask.astronomer.io/ I noticed an issue, previous responses are getting duplicated by first response and question.

More context: https://astronomer.slack.com/archives/C05QJA9LTR9/p1699263197141719

**Comment by pankajastro** [comment]
tried a few examples looks like something is not right with auto refresh
here is an example request https://ask.astronomer.io/requests/bc5476a6-8313-11ee-8587-2f5619e720f8 and it will give correct result since it has been refreshed

**Comment by Lee-W** [comment]
I'm trying to reproduce this but not able to. Is there any stable way to reproduce it? or has it been resolved?

**Comment by vatsrahul1001** [comment]
@Lee-W still reproducible, @pankajastro looked into this and was able to repro, not sure any fix was pushed for this

**Comment by Lee-W** [comment]
Thanks @vatsrahul1001 . I'm able to reproduce it both locally and dev now. Will take a look tomorrow

**Comment by vatsrahul1001** [comment]
Verified https://github.com/astronomer/ask-astro/pull/172 in dev LGTM
