### ISSUE TITLE
Feedback on slack should be on thread rather than on channel

### ISSUE THREAD

**Issue by sunank200** [astronomer/ask-astro#88]
Steven has suggested having the feedback on the thread rather than on the channel.

For example:
<img width="984" alt="Screenshot 2023-11-07 at 6 14 19 PM" src="https://github.com/astronomer/ask-astro/assets/8670962/d769e2ac-82ca-4fe9-b8ac-e3a9f89bee5c">
<img width="378" alt="Screenshot 2023-11-07 at 6 14 22 PM" src="https://github.com/astronomer/ask-astro/assets/8670962/e19eb736-ca75-4976-b09f-fdce42fc5958">

It should have posted this on a thread visible to the user.

**Comment by phanikumv** [comment]
Pankaj will analyze this today
